#include <stdio.h>
#include <stdlib.h>
#include "list.h"
#include "info.h"
#include <conio.h> //getch()

#define dim 200

int height = 4, width = 1;

struct {
    int x;
    int y;
} axis = {0,0};

void user_gui(); //generate a gui
void master_gui(); //racchiude tutte le funzioni inserite
void user_input(char userinput); //for listen input by keyboard

void user_gui() {

system("cls"); //for updating 

print_banner(); //print a banner
info_text(); //for generate a init text
const char *a[50] = {" ", "start", "exit", ""}; 

int i,j;
//this gui will generated by a matrix
for (j = 0; j < height; j++) { //height
    for (i = 0; i < width; i++) { //width
    if(i == axis.x && j == axis.y) {
        printf("user:~$ "); //user icon
    } else {
        printf("%s     : %s", ". ", a[j]);  
    }
  }
  printf("\n"); //doing a newline for any iteration of j
 }
}

//user input
void user_input(char userinput) {
	
    userinput = getch();
    
    switch (userinput) {
    case 'w': if(axis.y > 0) { axis.y--; } break; //move up
    case 's': if(axis.y < height - 1) { axis.y++; } break; //move down
    case ' ': if(axis.y == 1 ) { master_gui(); } else if(axis.y == 2) { exit(1); } break; //select
	
    default:
    	printf("nope");
        break;
    }
}


void master_gui() {

    //setup
	li *s = NULL;

	struct item n; 
    const char *priority[3] = {"high", "mid", "low"}; //poor method for diff a high mid or low value
	int time = 0;
	int day[DIM], month[DIM], year[DIM];
	char c[200][DIM], desc[200][DIM];
	
	new_list(s); //create a newList setupping all par to 0 or NULL
	
	printf("insert a number: ");
    scanf("%d", &n.intero); //pre-condition
    //the begin value haves impact on all functions
    
    input_str(c, desc, n); //for taking in input strings
    
    s = add_tail(s, n); //for taking in input numbers/elements
    printf("---------------\n");
    
    sorting(s, n); //sorting of the elements
    print_tail(s, priority, n);
    
    printf("---------------\n");
    printf("WARNING:u cant adding a year value below to 1000!\n");
    add_date(day, month, year, n); //take in input 3 values
	
	show_details(s, c, desc, day, month, year, n); //output that prints all details
	printf("---------------\n");
	
	printf("tempo da stimare: ");
	scanf("%d", &time);
	
	s = alter_elements(s, n); //modify the elements value
	printf("---------------\n");
	
	show_week(s, c, day, month, year, n, time); //prints in output the weekly reports
	  
	printf("---------------\n");
	system("echo press any key to back to the main menu && pause >nul");
	
	while (s != NULL) { //dealloc all after worked with allocations
        li *temp = s;
        free(s->vet);
        s = s->next;
        free(temp);
    }
    
    return;
}    





